package tube;
import javax.swing.JOptionPane;



/**
 *
 * @author lenovo
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Insert
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Home1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Insert = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setSize(new java.awt.Dimension(928, 640));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        Home.setBackground(new java.awt.Color(153, 153, 153));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });
        Home.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phptp 2/home-icon-silhouette (1).png"))); // NOI18N
        Home.add(jLabel4);
        jLabel4.setBounds(10, 20, 40, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Home");
        Home.add(jLabel6);
        jLabel6.setBounds(70, 10, 90, 60);

        Home1.setBackground(new java.awt.Color(153, 153, 153));
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Home1MousePressed(evt);
            }
        });
        Home1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phptp 2/home-icon-silhouette (1).png"))); // NOI18N
        Home1.add(jLabel10);
        jLabel10.setBounds(10, 20, 40, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Home");
        Home1.add(jLabel12);
        jLabel12.setBounds(70, 10, 90, 60);

        Home.add(Home1);
        Home1.setBounds(0, 140, 200, 80);

        jPanel2.add(Home);
        Home.setBounds(0, 160, 200, 80);

        Insert.setBackground(new java.awt.Color(102, 102, 102));
        Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InsertMousePressed(evt);
            }
        });
        Insert.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phptp 2/choice (1).png"))); // NOI18N
        Insert.add(jLabel7);
        jLabel7.setBounds(10, 20, 40, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Operation");
        Insert.add(jLabel8);
        jLabel8.setBounds(60, 10, 120, 50);

        jPanel2.add(Insert);
        Insert.setBounds(0, 240, 200, 80);

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel15.setText("Modern Academy   ");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 450, 180, 50);

        jLabel16.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel16.setText("Apps");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(70, 490, 60, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/academy (1).png"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(60, 530, 60, 50);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/football-ball (1).png"))); // NOI18N
        jPanel8.add(jLabel20);
        jLabel20.setBounds(60, 10, 80, 80);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(0, 10, 200, 100);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setText("2022-2023");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 590, 140, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("About");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 10, 110, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/jo/project (1).png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 0, 50, 60);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 320, 200, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 640);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("World Cup Highlights Tube");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(110, 0, 510, 60);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/button (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel3.add(exit);
        exit.setBounds(680, 0, 35, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/app-store (1).png"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(50, 10, 50, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(200, 0, 730, 60);

        jLabel18.setFont(new java.awt.Font("Gagalin", 1, 48)); // NOI18N
        jLabel18.setText("FIFA World Cup 2022");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 560, 460, 70);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/world-cup (1).png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(690, 560, 50, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/wallpaperflare.com_wallpaper (14) (1)_1.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(852, 628));
        jLabel2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 60, 730, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMousePressed

    private void InsertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertMousePressed
        // TODO add your handling code here:
         new Insert().show();
        dispose();
    }//GEN-LAST:event_InsertMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null, "Are you sure you want to exit ?", "World Cap Highlights Tube", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMousePressed

    private void Home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home1MousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        new About().show();
        dispose();
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home1;
    private javax.swing.JPanel Insert;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
